///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RecordModel {
/*
{
  "clientId": "",
  "createdOn": "",
  "endTime": "",
  "freelancerEmail": "",
  "freelancerId": "",
  "freelancerName": "",
  "projectId": "",
  "recordComment": "",
  "recordId": "",
  "recordName": "",
  "startTime": ""
}
*/

  String? clientId;
  String? createdOn;
  String? endTime;
  String? freelancerEmail;
  String? freelancerId;
  String? freelancerName;
  String? projectId;
  String? recordComment;
  String? recordId;
  String? recordName;
  String? startTime;

  RecordModel({
    this.clientId,
    this.createdOn,
    this.endTime,
    this.freelancerEmail,
    this.freelancerId,
    this.freelancerName,
    this.projectId,
    this.recordComment,
    this.recordId,
    this.recordName,
    this.startTime,
  });
  RecordModel.fromJson(Map<String, dynamic> json) {
    clientId = json['clientId']?.toString();
    createdOn = json['createdOn']?.toString();
    endTime = json['endTime']?.toString();
    freelancerEmail = json['freelancerEmail']?.toString();
    freelancerId = json['freelancerId']?.toString();
    freelancerName = json['freelancerName']?.toString();
    projectId = json['projectId']?.toString();
    recordComment = json['recordComment']?.toString();
    recordId = json['recordId']?.toString();
    recordName = json['recordName']?.toString();
    startTime = json['startTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['clientId'] = clientId;
    data['createdOn'] = createdOn;
    data['endTime'] = endTime;
    data['freelancerEmail'] = freelancerEmail;
    data['freelancerId'] = freelancerId;
    data['freelancerName'] = freelancerName;
    data['projectId'] = projectId;
    data['recordComment'] = recordComment;
    data['recordId'] = recordId;
    data['recordName'] = recordName;
    data['startTime'] = startTime;
    return data;
  }
}