import 'package:flutter/material.dart';

class AppColors {
  static const Color successColor = Color(0xff41c188);
  static const Color successLightColor = Color(0xffEBF9F3);
  static const Color greenColor = Color(0xffD1FEEA);
  static const Color backgroundColor = Color(0xff03042b);
  static const Color pageBackgroundColor = Color(0xff396196);
  static const Color headingColor = Color(0xff1c295d);
  static const Color hintTextColor = Color(0xff707070);
  static const Color hintGrey = Color(0xFF9B9B9B);
  static const Color hintEditTextColor = Color(0xffC1C1C1);
  static const Color primaryColor = Color(0xff055ED2);
  static const Color iconColor = Color(0xff8290ab);
  static const Color textColor = Color(0xff99a6c5);
  static const Color settingBackgroundColor = Color(0xffffe6e2);
  static const Color settingTextColor = Color(0xfffc573b);
  static const Color multiPlayerBackgroundColor = Color(0xffd6eafd);
  static const Color multiPlayerTextColor = Color(0xff51a8f9);
  static const Color singlePlayerBackgroundColor = Color(0xffffebdc);
  static const Color singlePlayerTextColor = Color(0xffff9911);
  static const Color settingAccountDetailBackgroundColor = Color(0xffF2F6FE);
  static const Color settingLegalBackgroundColor = Color(0xffE9ECEF);
  static const Color titleColor = Color(0xff1C295D);
  static const Color dividerColor = Color(0xffEFEFEF);
  static const Color editButtonColor = Color(0xff54C1FB);
  static const Color fbButtonColor = Color(0xff2D5399);
  static const Color endlessModeColor = Color(0xff9694FF);
  static const Color timedModeColor = Color(0xff57CAEB);
  static const Color reviewModeColor = Color(0xff435EBE);
  static const Color overviewModeColor = Color(0xff5DDAB4);
  static const Color flashcardsModeColor = Color(0xffFF817E);
  static const Color timedModeBackgroundColor = Color(0xffFFAF01);
  static const Color behavioralScienceBackgroundColor = Color(0xffEEAF63);
  static const Color biologyBackgroundColor = Color(0xffF3A282);
  static const Color generalChemistryBackgroundColor = Color(0xff743250);
  static const Color organicChemistryBackgroundColor = Color(0xff7D9A89);
  static const Color physicsBackgroundColor = Color(0xffE5D1D9);
  static const Color bioChemistryBackgroundColor = Color(0xffBBB0C0);
  static const Color lightGrey = Color(0xffF9F9F9);
  static const Color lightPurple = Color(0xffEAEAFA);
  static const Color lightPink = Color(0xffFED1E2);
  static const Color lightYellow = Color(0xffFEF5CA);
  static const Color wrongAnswerBackground = Color(0xffFFD9D8);
  static const Color wrongAnswerTextColor = Color(0xffFF0606);
  static const Color notAttemptedAnswerTextColor = Color(0xff7B8085);
  static const Color correctAnswerBackgroundColor = Color(0xffA7FFD8);
  static const Color questionBackgroundColor = Color(0xffFFE6AC);

  ///-----------------------------------------------------------------------------
  static const Color bgDenim = Color(0xFF05062D);
  static const Color bgGreen = Color(0xFF41C188);
  static const Color bgPurple = Color(0xFF4145D1);
  static const Color bgBlue = Color(0xFF396196);
  static const Color bgWhite = Color(0xFFFFFFFF);
  static const Color bgLight = Color(0xFFF5F5F5);
  static const Color textWhite = Color(0xFFFFFFFF);
  static const Color textLight = Color(0xFFC7C7C7);
  static const Color textDenim = Color(0xFF05062D);
}